[package]
name = "mp4_to_vcam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
virtualcam-rs = { path = "../../../virtualcam-rs" }

ffmpeg-next = { version = "6.0.0", features = ["static"] }
